void eglBindAPI() {}
void eglBindTexImage() {}
void eglChooseConfig() {}
void eglCopyBuffers() {}
void eglCreateContext() {}
void eglCreatePbufferFromClientBuffer() {}
void eglCreatePbufferSurface() {}
void eglCreatePixmapSurface() {}
void eglCreateWindowSurface() {}
void eglDestroyContext() {}
void eglDestroySurface() {}
void eglGetConfigAttrib() {}
void eglGetConfigs() {}
void eglGetCurrentContext() {}
void eglGetCurrentDisplay() {}
void eglGetCurrentSurface() {}
void eglGetDisplay() {}
void eglGetError() {}
void eglGetProcAddress() {}
void eglInitialize() {}
void eglMakeCurrent() {}
void eglQueryAPI() {}
void eglQueryContext() {}
void eglQueryString() {}
void eglQuerySurface() {}
void eglReleaseTexImage() {}
void eglReleaseThread() {}
void eglSurfaceAttrib() {}
void eglSwapBuffers() {}
void eglSwapInterval() {}
void eglTerminate() {}
void eglWaitClient() {}
void eglWaitGL() {}
void eglWaitNative() {}
