void glActiveTexture() {}
void glAttachShader() {}
void glBindAttribLocation() {}
void glBindBuffer() {}
void glBindFramebuffer() {}
void glBindRenderbuffer() {}
void glBindTexture() {}
void glBlendColor() {}
void glBlendEquation() {}
void glBlendEquationSeparate() {}
void glBlendFunc() {}
void glBlendFuncSeparate() {}
void glBufferData() {}
void glBufferSubData() {}
void glCheckFramebufferStatus() {}
void glClear() {}
void glClearColor() {}
void glClearDepthf() {}
void glClearStencil() {}
void glColorMask() {}
void glCompileShader() {}
void glCompressedTexImage2D() {}
void glCompressedTexSubImage2D() {}
void glCopyTexImage2D() {}
void glCopyTexSubImage2D() {}
void glCreateProgram() {}
void glCreateShader() {}
void glCullFace() {}
void glDeleteBuffers() {}
void glDeleteFramebuffers() {}
void glDeleteProgram() {}
void glDeleteRenderbuffers() {}
void glDeleteShader() {}
void glDeleteTextures() {}
void glDepthFunc() {}
void glDepthMask() {}
void glDepthRangef() {}
void glDetachShader() {}
void glDisable() {}
void glDisableVertexAttribArray() {}
void glDrawArrays() {}
void glDrawElements() {}
void glEnable() {}
void glEnableVertexAttribArray() {}
void glFinish() {}
void glFlush() {}
void glFramebufferRenderbuffer() {}
void glFramebufferTexture2D() {}
void glFrontFace() {}
void glGenBuffers() {}
void glGenerateMipmap() {}
void glGenFramebuffers() {}
void glGenRenderbuffers() {}
void glGenTextures() {}
void glGetActiveAttrib() {}
void glGetActiveUniform() {}
void glGetAttachedShaders() {}
void glGetAttribLocation() {}
void glGetBooleanv() {}
void glGetBufferParameteriv() {}
void glGetError() {}
void glGetFloatv() {}
void glGetFramebufferAttachmentParameteriv() {}
void glGetIntegerv() {}
void glGetProgramInfoLog() {}
void glGetProgramiv() {}
void glGetRenderbufferParameteriv() {}
void glGetShaderInfoLog() {}
void glGetShaderiv() {}
void glGetShaderPrecisionFormat() {}
void glGetShaderSource() {}
void glGetString() {}
void glGetTexParameterfv() {}
void glGetTexParameteriv() {}
void glGetUniformfv() {}
void glGetUniformiv() {}
void glGetUniformLocation() {}
void glGetVertexAttribfv() {}
void glGetVertexAttribiv() {}
void glGetVertexAttribPointerv() {}
void glHint() {}
void glIsBuffer() {}
void glIsEnabled() {}
void glIsFramebuffer() {}
void glIsProgram() {}
void glIsRenderbuffer() {}
void glIsShader() {}
void glIsTexture() {}
void glLineWidth() {}
void glLinkProgram() {}
void glPixelStorei() {}
void glPolygonOffset() {}
void glReadPixels() {}
void glReleaseShaderCompiler() {}
void glRenderbufferStorage() {}
void glSampleCoverage() {}
void glScissor() {}
void glShaderBinary() {}
void glShaderSource() {}
void glStencilFunc() {}
void glStencilFuncSeparate() {}
void glStencilMask() {}
void glStencilMaskSeparate() {}
void glStencilOp() {}
void glStencilOpSeparate() {}
void glTexImage2D() {}
void glTexParameterf() {}
void glTexParameterfv() {}
void glTexParameteri() {}
void glTexParameteriv() {}
void glTexSubImage2D() {}
void glUniform1f() {}
void glUniform1fv() {}
void glUniform1i() {}
void glUniform1iv() {}
void glUniform2f() {}
void glUniform2fv() {}
void glUniform2i() {}
void glUniform2iv() {}
void glUniform3f() {}
void glUniform3fv() {}
void glUniform3i() {}
void glUniform3iv() {}
void glUniform4f() {}
void glUniform4fv() {}
void glUniform4i() {}
void glUniform4iv() {}
void glUniformMatrix2fv() {}
void glUniformMatrix3fv() {}
void glUniformMatrix4fv() {}
void glUseProgram() {}
void glValidateProgram() {}
void glVertexAttrib1f() {}
void glVertexAttrib1fv() {}
void glVertexAttrib2f() {}
void glVertexAttrib2fv() {}
void glVertexAttrib3f() {}
void glVertexAttrib3fv() {}
void glVertexAttrib4f() {}
void glVertexAttrib4fv() {}
void glVertexAttribPointer() {}
void glViewport() {}
